### ISSUE TITLE
Quick question about defaults

### ISSUE THREAD

**Issue by khanbalam** [fabiospampinato/pastebin-monitor#3]
I just downloaded this project and it is quite awesome, I just have a doubt about the default PATH in Windows for the file where the pasties are saved.

For example I run this command "py -3 pastebin_crawler.py archive.txt string" where archive is the name of the file and sring the word I'm looking for. So I assume it will save it in the same directory in which I am executing the code, is that so?

I use py -3 so it used python 3.5.2 instead of 2.7.11. I did install the dependencies for the 3.5..2 version.

I mean the script is running and it has find some pasties:

[2016/08/17 10:41:09] Getting pastes

But I do not see the file in this directory.

Or does it go to the path of python script?

Thanks for this awesome code and thanks for reading.

**Comment by khanbalam** [comment]
Nevermind that question.

I see how it runs and how to get what I need.

Thank you and best regards.

**Comment by Jorl17** [comment]
Hi @khanbalam, I just saw this. I keep a fork at https://github.com/Jorl17/Pastebin-Crawler. This repository has had most of my changes reintegrated which incorporated a fairly large rewrite. If you have questions and issues, perhaps you can place them at https://github.com/Jorl17/Pastebin-Crawler , since I think I'm more familiar with the code at the moment. Glad it was useful :)
